// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD6Kzr-nrtk8Q3snIOTBgIC01LYf-94wE',
    appId: '1:1706608555:web:2c769470205dbe8454f4ee',
    messagingSenderId: '1706608555',
    projectId: 'food-delivery-cf117',
    authDomain: 'food-delivery-cf117.firebaseapp.com',
    storageBucket: 'food-delivery-cf117.firebasestorage.app',
    measurementId: 'G-JX6XKP1TQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW7L-9VxDqu91h6DODtt4Xq_NBqivfRGk',
    appId: '1:1706608555:android:3b107ae617a3313354f4ee',
    messagingSenderId: '1706608555',
    projectId: 'food-delivery-cf117',
    storageBucket: 'food-delivery-cf117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmu_Vky-p2K5KLVzDFEiMMtCaCMm3P3JY',
    appId: '1:1706608555:ios:a9744c51416089af54f4ee',
    messagingSenderId: '1706608555',
    projectId: 'food-delivery-cf117',
    storageBucket: 'food-delivery-cf117.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmu_Vky-p2K5KLVzDFEiMMtCaCMm3P3JY',
    appId: '1:1706608555:ios:a9744c51416089af54f4ee',
    messagingSenderId: '1706608555',
    projectId: 'food-delivery-cf117',
    storageBucket: 'food-delivery-cf117.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD6Kzr-nrtk8Q3snIOTBgIC01LYf-94wE',
    appId: '1:1706608555:web:6fc9ab59f631c6c054f4ee',
    messagingSenderId: '1706608555',
    projectId: 'food-delivery-cf117',
    authDomain: 'food-delivery-cf117.firebaseapp.com',
    storageBucket: 'food-delivery-cf117.firebasestorage.app',
    measurementId: 'G-57LD1N26SM',
  );
}
